### ISSUE TITLE
Create a directory of previous versions and a publish mechanism

### ISSUE THREAD

**Issue by andrewpatto** [ga4gh/data-security#102]
See for example FHIR

http://hl7.org/fhir/directory.html

**Comment by TomConner** [comment]
I manually published the 1.2 release as a copy of the unversioned root so now we have:

| Version                                                                             | Changes                        |
| ----------------------------------------------------------------------------------- | ------------------------------ |
| [1.0](https://github.com/ga4gh/data-security/blob/AAIv1.0/AAI/AAIConnectProfile.md) | Initial release                |
| [1.2](https://ga4gh.github.io/data-security/1.2/aai-openid-connect-profile) ([latest](https://ga4gh.github.io/data-security/aai-openid-connect-profile))    | [Changes in 1.2](https://ga4gh.github.io/data-security/draft-1.3/changes-1_2)  |
| [1.3 draft](https://ga4gh.github.io/data-security/draft-1.3/aai-openid-connect-profile)                                             | [Changes in 1.3](https://ga4gh.github.io/data-security/draft-1.3/changes-1_3)  |
