### ISSUE TITLE
Broken links in the policy markdown

### ISSUE THREAD

**Issue by delocalizer** [ga4gh/data-security#119]
There are several broken links to important resources in the policy doc, for example
* https://www.ga4gh.org/ga4ghtoolkit/regulatoryandethics/framework-for-responsible-sharing-genomic-and-health-related-data/
* https://www.ga4gh.org/docs/ga4ghtoolkit/data-security/Privacy-and-Security-Policy.pdf
* https://www.ga4gh.org/wp-content/uploads/Privacy-and-Security-Policy.pdf
* https://www.nihr.ac.uk/about-us/CCF/policy-and-standards/research-passports.htm
* http://hl7.org/implement/standards/fhir/v3/Confidentiality/

**Comment by martin-kuba** [comment]
merged fix, thanks @delocalizer !
