### ISSUE TITLE
Claim polling heading

### ISSUE THREAD

**Issue by mikael-linden** [ga4gh/data-security#21]
_**Claim Polling**: Clients MAY use access tokens, including Embedded Tokens,..._

Can this be renamed to "access token polling" just to indicate (and avoid a misconception) that this is for using an (embedded) access token to poll claims in userinfo but there is no mechanism defined for polling embedded document tokens.

**Comment by davidbernick** [comment]
I have no issue with that.

bernick_mikael_issues 61c9c77

**Comment by davidbernick** [comment]
https://github.com/ga4gh/data-security/pull/26
