### ISSUE TITLE
Orphan terms in JWT format section

### ISSUE THREAD

**Issue by mikael-linden** [ga4gh/data-security#22]
**GA4GH JWT Format** section:
_The access token and JWT with full claims use the same format, though the JWT with the full claims will have extended claims._

Terms _full claims_ and _extended claims_ are not used elsewhere in the document. Can you add descriptive text or a well define term?

**Comment by davidbernick** [comment]
this is probably vestigal.
bernick_mikael_issues f940572

**Comment by davidbernick** [comment]
https://github.com/ga4gh/data-security/pull/26
