### ISSUE TITLE
Requirement on claims in access tokens 

### ISSUE THREAD

**Issue by mikael-linden** [ga4gh/data-security#23]
**Embedded Access Token Format** section:
_4. The payload claims MUST contain at least one GA4GH Claim (<ga4gh-spec-claims>)_

Do we still keep this requirement, given the size of embedded claims?

N.B. This requirement is not present in  **Access_token issued by Broker** section , disabling a broker from placing an access token given by an upstream broker to a downstream embedded token.

**Comment by davidbernick** [comment]
@cdvoisin what do you think? Guidance?

**Comment by cdvoisin** [comment]
Perhaps in the more generic sense, Mikael raises a good point. For passports, this form of embedding is not allowed as Passport Visas are distinct and do not rely on /userinfo mechanisms. However, this is already spelled out in the Passport Visa Format section, so removing the requirement from AAI Embedded Tokens would be fine.

Let's change it to OPTIONAL.
