### ISSUE TITLE
Mismatch of requirement and example in Embedded document token

### ISSUE THREAD

**Issue by mikael-linden** [ga4gh/data-security#24]
**Embedded Document Token Format** section:

_jti: RECOMMENDED. A unique identifier for the token as per RFC7519 Section 4.1.7 is RECOMMENDED._
However, `jti` is not present in the example.

**Comment by davidbernick** [comment]
bernick_mikael_issues edad340

**Comment by davidbernick** [comment]
https://github.com/ga4gh/data-security/pull/26
